//! The docs' reference pages that come from the core: every setting, from
//! the table `settings.json` is checked against, and every manifest key,
//! from the table beside the loader. Built only with `--features docs`, and
//! printed by the `wicket-docs` binary.

use std::fmt::Write;

use crate::{plugins, settings};

/// The settings reference: every key, what it holds, its default and what
/// it does.
pub fn settings_page() -> String {
    let mut page = String::from(
        "---\ntitle: Settings reference\ndescription: \"Every key in settings.json, generated from the settings the app checks.\"\n---\n\n\
         <!-- Generated by `wicket-docs settings` from the core's settings table. Do not edit: change the table instead. -->\n\n\
         Every key in `settings.json`, the file in your data directory that the app's Settings writes. \
         Keys are dotted paths into the file: `appearance.theme` is `{\"appearance\": {\"theme\": …}}`. \
         For what each section of Settings does, see [Settings](/docs/using/settings/).\n\n",
    );
    page.push_str("| Key | Value | Default | What it does |\n|---|---|---|---|\n");
    for (key, value, default, does) in settings::reference() {
        let _ = writeln!(
            page,
            "| `{key}` | {} | `{}` | {} |",
            cell(&value),
            cell(&default),
            cell(does)
        );
    }
    page.push_str(
        "\n## Plugin settings\n\n\
         Under `plugins.<name>`, each plugin keeps the settings its manifest declares in `settings_schema`, \
         checked against that schema. See [Settings and keys of a plugin](/docs/building/settings-and-keys/).\n\n\
         ## Changing settings\n\n\
         The app writes the file as settings change, and notices an edit made outside it. \
         A key it does not know is kept as it is. A script can read and change settings through the local API, \
         which checks every change the same way:\n\n\
         ```sh\n\
         curl http://127.0.0.1:4747/api/v1/settings\n\
         curl -X PATCH http://127.0.0.1:4747/api/v1/settings \\\n  -H 'content-type: application/json' -d '{\"notifications\": {\"sound\": false}}'\n\
         ```\n",
    );
    page
}

/// The manifest reference: every key a plugin's `manifest.json` may set.
pub fn manifest_page() -> String {
    let mut page = String::from(
        "---\ntitle: Manifest reference\ndescription: \"Every key of a plugin's manifest.json, generated from the keys Wicket reads.\"\n---\n\n\
         <!-- Generated by `wicket-docs manifest` from the core's manifest keys. Do not edit: change the table instead. -->\n\n\
         Every key a plugin's `manifest.json` may set. The manifest sits at the root of the plugin's folder; \
         paths in it are relative to that folder and cannot leave it. \
         For a walk through writing one, see [Writing a plugin](/docs/building/writing/).\n\n\
         ```json title=\"manifest.json\"\n{\n  \"name\": \"ticket_triage\",\n  \"version\": \"0.1.0\",\n  \"title\": \"Ticket triage\",\n  \"icon\": \"ticket\",\n  \
         \"payload_schema\": { \"$ref\": \"schemas/payload.schema.json\" },\n  \"decision_schema\": { \"$ref\": \"schemas/decision.schema.json\" },\n  \
         \"entry\": \"view/index.html\",\n  \"min_height\": 200\n}\n```\n\n",
    );
    page.push_str("| Key | Required | Value | What it does |\n|---|---|---|---|\n");
    for (key, required, value, does) in plugins::MANIFEST_KEYS {
        let _ = writeln!(
            page,
            "| `{key}` | {} | {} | {} |",
            if *required { "Yes" } else { "" },
            cell(value),
            cell(does)
        );
    }
    page.push_str(
        "\nSchemas are JSON Schema 2020-12. The shapes of `settings_schema` and `shortcuts` are in \
         [Settings and keys of a plugin](/docs/building/settings-and-keys/), and `decision_template` in \
         [Writing a plugin](/docs/building/writing/#decisions-as-markdown). \
         `npx wicket-plugin check` reads a folder the way the app does and says what it would refuse.\n",
    );
    page
}

/// Text that sits in a table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    #[test]
    fn every_setting_is_in_the_settings_page() {
        let page = super::settings_page();
        for (key, _, _, _) in crate::settings::reference() {
            assert!(page.contains(&format!("| `{key}` |")), "{key} is missing");
        }
        assert!(page.contains("| `port` | a port, 1 to 65535 | `4747` |"));
        assert!(page.starts_with("---\ntitle: Settings reference\n"));
    }

    #[test]
    fn every_manifest_key_is_in_the_manifest_page() {
        let page = super::manifest_page();
        for (key, ..) in crate::plugins::MANIFEST_KEYS {
            assert!(page.contains(&format!("| `{key}` |")), "{key} is missing");
        }
        assert!(page.contains("| `name` | Yes |"));
    }
}
