//! The docs' reference pages that come from the core: every setting, from
//! the table `settings.json` is checked against, and every manifest key,
//! from the manifest's JSON Schema. Built only with `--features docs`, and
//! printed by the `pinrail-docs` binary.

use std::fmt::Write;

use serde_json::Value;

use crate::{plugins, settings};

/// The settings reference: every key, what it holds, its default and what
/// it does.
pub fn settings_page() -> String {
    let mut page = String::from(
        "---\ntitle: Settings reference\ndescription: \"Every key in settings.json, generated from the settings the app checks.\"\n---\n\n\
         <!-- Generated by `pinrail-docs settings` from the core's settings table. Do not edit: change the table instead. -->\n\n\
         Every key in `settings.json`, the file in your data directory that the app's Settings writes. \
         Keys are dotted paths into the file: `appearance.theme` is `{\"appearance\": {\"theme\": …}}`. \
         For what each section of Settings does, see [Settings](/docs/using/settings/).\n\n",
    );
    page.push_str("| Key | Value | Default | What it does |\n|---|---|---|---|\n");
    for (key, value, default, does) in settings::reference() {
        let _ = writeln!(
            page,
            "| `{key}` | {} | `{}` | {} |",
            cell(&value),
            cell(&default),
            cell(does)
        );
    }
    page.push_str(
        "\n## Plugin settings\n\n\
         Under `plugins.<name>`, each plugin keeps the settings its manifest declares in `settings_schema`, \
         checked against that schema. See [Settings and keys of a plugin](/docs/building/settings-and-keys/).\n\n\
         ## Link permissions\n\n\
         Under `links.<name>`, Pinrail keeps the sites a plugin may open without asking: `source`, where the plugin was installed from \
         when the sites were allowed, and `origins`, such as `[\"https://github.com\"]`. The permission applies only while the plugin is \
         installed from that source, and removing the plugin removes it. The app writes it when you allow a site, and a plugin's view \
         cannot change it.\n\n\
         ## Changing settings\n\n\
         The app writes the file as settings change, and notices an edit made outside it. \
         A key it does not know is kept as it is. A script can read and change settings through the local API, \
         which checks every change the same way:\n\n\
         ```sh\n\
         curl http://127.0.0.1:4747/api/v1/settings\n\
         curl -X PATCH http://127.0.0.1:4747/api/v1/settings \\\n  -H 'content-type: application/json' -d '{\"notifications\": {\"sound\": false}}'\n\
         ```\n",
    );
    page
}

/// The manifest reference, from the manifest's JSON Schema: every key, in
/// the schema's order, whether it is required, what it holds and what it
/// does, in the schema's own words.
pub fn manifest_page() -> String {
    let schema: Value =
        serde_json::from_str(plugins::MANIFEST_SCHEMA).expect("the manifest schema is JSON");
    let required: Vec<&str> = schema["required"]
        .as_array()
        .map(|keys| keys.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let mut page = String::from(
        "---\ntitle: Manifest reference\ndescription: \"Every key of a plugin's manifest.json, generated from the manifest's JSON Schema.\"\n---\n\n\
         <!-- Generated by `pinrail-docs manifest` from pinrail-plugin/schemas/manifest.schema.json. Do not edit: change the schema instead. -->\n\n",
    );
    if let Some(what) = schema["description"].as_str() {
        let _ = writeln!(page, "{what}\n");
    }
    page.push_str(
        "Pinrail checks every manifest against its JSON Schema, `manifest.schema.json` in the `pinrail-plugin` package, \
         before it loads or installs a plugin. Point your editor at it with `$schema` to check a manifest as you write it. \
         For a walk through writing one, see [Writing a plugin](/docs/building/writing/).\n\n\
         | Key | Required | Value | What it does |\n|---|---|---|---|\n",
    );
    for (key, property) in schema["properties"].as_object().into_iter().flatten() {
        if key == "$schema" {
            continue;
        }
        let _ = writeln!(
            page,
            "| `{key}` | {} | {} | {} |",
            if required.contains(&key.as_str()) {
                "Yes"
            } else {
                ""
            },
            cell(&value(property)),
            cell(property["description"].as_str().unwrap_or_default())
        );
    }
    let features: Vec<String> = plugins::MANIFEST_FEATURES
        .iter()
        .map(|k| format!("`{k}`"))
        .collect();
    let (last, rest) = features
        .split_last()
        .expect("some keys cost only a feature");
    let _ = write!(
        page,
        "\nIf {} or {last} is invalid, the plugin loses only that feature, and the problem is shown on its row in Settings. \
         Any other invalid key means the plugin cannot be used. The formats of `settings_schema` and `shortcuts` are described in \
         [Settings and keys of a plugin](/docs/building/settings-and-keys/). \
         `pinrail plugins check <folder>` checks a plugin folder against the same schema, together with the files the manifest names.\n",
        rest.join(", ")
    );
    page
}

/// What a property holds, from its types, pattern, bounds and default.
fn value(property: &Value) -> String {
    if let Some(branches) = property["oneOf"].as_array() {
        return branches.iter().map(value).collect::<Vec<_>>().join(", or ");
    }
    let types: Vec<&str> = match &property["type"] {
        Value::String(t) => vec![t.as_str()],
        Value::Array(ts) => ts.iter().filter_map(Value::as_str).collect(),
        _ => vec![],
    };
    let mut parts: Vec<String> = types
        .iter()
        .filter(|t| **t != "null")
        .map(|t| match *t {
            "object" if property["properties"].is_object() => {
                let keys: Vec<String> = property["properties"]
                    .as_object()
                    .unwrap()
                    .keys()
                    .map(|k| k.to_string())
                    .collect();
                format!("`{{{}}}`", keys.join(", "))
            }
            "array" if property["items"]["properties"].is_object() => {
                let keys: Vec<String> = property["items"]["properties"]
                    .as_object()
                    .unwrap()
                    .keys()
                    .map(|k| k.to_string())
                    .collect();
                format!("a list of `{{{}}}`", keys.join(", "))
            }
            "object" => "an object".into(),
            "array" => "a list".into(),
            "integer" => match property["minimum"].as_i64() {
                Some(min) => format!("an integer, at least {min}"),
                None => "an integer".into(),
            },
            "boolean" => "`true` or `false`".into(),
            other => format!("a {other}"),
        })
        .collect();
    // a pattern plain enough to read says more than its description can;
    // one full of escapes is left to the description
    if let (Some(pattern), Some(first)) = (
        property["pattern"]
            .as_str()
            .filter(|p| p.starts_with('^') && p.ends_with('$') && !p.contains('\\')),
        parts.first_mut(),
    ) {
        first.push_str(&format!(" matching `{pattern}`"));
    }
    if types.contains(&"null") {
        parts.push("`null`".into());
    }
    let mut text = parts.join(", or ");
    if let Some(default) = property.get("default") {
        text.push_str(&format!("; defaults to `{default}`"));
    }
    text
}

/// Text that sits in a table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    #[test]
    fn every_setting_is_in_the_settings_page() {
        let page = super::settings_page();
        for (key, _, _, _) in crate::settings::reference() {
            assert!(page.contains(&format!("| `{key}` |")), "{key} is missing");
        }
        assert!(page.contains("| `port` | a port, 1 to 65535 | `4747` |"));
        assert!(page.starts_with("---\ntitle: Settings reference\n"));
    }

    #[test]
    fn every_key_of_the_manifest_schema_is_in_the_manifest_page() {
        let page = super::manifest_page();
        let schema: serde_json::Value =
            serde_json::from_str(crate::plugins::MANIFEST_SCHEMA).unwrap();
        for key in schema["properties"]
            .as_object()
            .unwrap()
            .keys()
            .filter(|k| *k != "$schema")
        {
            assert!(page.contains(&format!("| `{key}` |")), "{key} is missing");
        }
        assert!(page.contains("| `name` | Yes | a string matching `^[a-z][a-z0-9_-]*$` |"));
        assert!(page.contains("| `min_height` |  | an integer, at least 1; defaults to `400` |"));
    }
}
