//! The CLI reference page of the docs, rendered from the clap definition, so
//! the page says what the binary does. Built only with `--features docs`
//! and reached through `wicket --markdown-help`; the installed CLI carries
//! none of it.

use std::collections::BTreeMap;
use std::fmt::Write;

use clap::{Arg, Command};

use crate::{EXIT_CLOSED, EXIT_DISCARDED, EXIT_ERROR, EXIT_REFUSED, EXIT_TIMEOUT};

/// Every way a command ends, in the order a reader looks them up.
const EXITS: &[(u8, &str)] = &[
    (
        0,
        "Done. For `wait` and `submit --wait`: the review was decided.",
    ),
    (
        EXIT_ERROR,
        "Error: bad arguments, the server unreachable, a file that could not be read or written.",
    ),
    (
        EXIT_REFUSED,
        "The server refused the request, for example a payload the plugin's schema rejects. Its answer is on stderr.",
    ),
    (
        EXIT_CLOSED,
        "The review was withdrawn by the agent, or expired, before anyone decided.",
    ),
    (
        EXIT_TIMEOUT,
        "`--timeout` ran out. The review is still pending.",
    ),
    (
        EXIT_DISCARDED,
        "The person discarded the review: stop the work it was gating.",
    ),
];

/// The variables the CLI reads outside clap, beside the ones flags declare.
const ENVIRONMENT: &[(&str, &str)] = &[
    (
        "WICKET_DATA_DIR",
        "Where the running server's `server.json` is, to find it; also where a server the CLI starts keeps its data.",
    ),
    (
        "WICKET_PORT",
        "The port to try when no server advertises itself. Defaults to 4747.",
    ),
    (
        "WICKET_SERVER_CMD",
        "How to start a server when none is running, run through `sh -c`. `submit` and `serve` use it.",
    ),
];

/// The whole page: front matter, global flags, every command, exit codes and
/// the environment.
pub fn render(root: &Command) -> String {
    let mut page = String::new();
    let name = root.get_name();
    let _ = writeln!(
        page,
        "---\ntitle: CLI reference\ndescription: \"Every {name} command and flag, generated from the CLI itself.\"\n---\n"
    );
    let _ = writeln!(
        page,
        "<!-- Generated by `{name} --markdown-help` from the CLI's definition. Do not edit: change the CLI's help text instead. -->\n"
    );
    let _ = writeln!(
        page,
        "Every command and flag of `{name}`, from the same definition `{name} --help` prints. For the commands in use, see [The CLI](/docs/agents/cli/).\n"
    );

    let globals: Vec<&Arg> = visible_args(root).filter(|a| a.is_global_set()).collect();
    if !globals.is_empty() {
        page.push_str("## Global flags\n\nEvery command accepts these.\n\n");
        table(&mut page, &globals);
    }

    page.push_str("## Commands\n\n");
    for sub in root.get_subcommands().filter(|c| !c.is_hide_set()) {
        command(&mut page, sub, &[name]);
    }

    page.push_str("## Exit codes\n\n| Code | Meaning |\n|---|---|\n");
    for (code, meaning) in EXITS {
        let _ = writeln!(page, "| `{code}` | {meaning} |");
    }

    page.push_str("\n## Environment\n\n| Variable | Used for |\n|---|---|\n");
    for (var, what) in environment(root) {
        let _ = writeln!(page, "| `{var}` | {} |", cell(&what));
    }
    page
}

/// One command's section, then its own subcommands under it.
fn command(page: &mut String, cmd: &Command, parents: &[&str]) {
    let path: Vec<&str> = parents.iter().copied().chain([cmd.get_name()]).collect();
    let _ = writeln!(page, "### `{}`\n", path.join(" "));
    if let Some(about) = cmd.get_long_about().or(cmd.get_about()) {
        let _ = writeln!(page, "{}\n", sentence(&about.to_string()));
    }
    let aliases: Vec<&str> = cmd.get_visible_aliases().chain(cmd.get_aliases()).collect();
    if !aliases.is_empty() {
        let list: Vec<String> = aliases.iter().map(|a| format!("`{a}`")).collect();
        let _ = writeln!(page, "Also: {}.\n", list.join(", "));
    }
    let _ = writeln!(page, "```sh\n{}\n```\n", usage(cmd, &path));

    let args: Vec<&Arg> = visible_args(cmd).collect();
    if !args.is_empty() {
        table(page, &args);
    }
    for sub in cmd.get_subcommands().filter(|c| !c.is_hide_set()) {
        command(page, sub, &path);
    }
}

/// `wicket submit <PLUGIN> --title <TITLE> [OPTIONS]`: what must be given,
/// then that more is possible.
fn usage(cmd: &Command, path: &[&str]) -> String {
    let mut parts: Vec<String> = path.iter().map(|p| p.to_string()).collect();
    if cmd.has_subcommands() {
        parts.push(
            if cmd.is_subcommand_required_set() {
                "<COMMAND>"
            } else {
                "[COMMAND]"
            }
            .into(),
        );
    }
    let mut optional = false;
    for arg in visible_args(cmd) {
        if arg.is_positional() {
            let name = value_name(arg);
            parts.push(if arg.is_required_set() {
                format!("<{name}>")
            } else {
                format!("[{name}]")
            });
        } else if arg.is_required_set() {
            parts.push(flag(arg));
        } else {
            optional = true;
        }
    }
    if optional {
        parts.push("[OPTIONS]".into());
    }
    parts.join(" ")
}

/// Arguments, positionals first, then flags as the definition orders them.
fn table(page: &mut String, args: &[&Arg]) {
    page.push_str("| Argument | Description |\n|---|---|\n");
    let (positional, flags): (Vec<&&Arg>, Vec<&&Arg>) =
        args.iter().partition(|a| a.is_positional());
    for arg in positional.into_iter().chain(flags) {
        let name = if arg.is_positional() {
            format!("`<{}>`", value_name(arg))
        } else {
            format!("`{}`", flag(arg))
        };
        let _ = writeln!(page, "| {} | {} |", cell(&name), cell(&describe(arg)));
    }
    page.push('\n');
}

/// The help text, then what is required, the default, the choices, the
/// variable that sets it and other spellings.
fn describe(arg: &Arg) -> String {
    let mut text = arg
        .get_long_help()
        .or(arg.get_help())
        .map(|h| sentence(&h.to_string()))
        .unwrap_or_default();
    let mut notes = Vec::new();
    if arg.is_required_set() && !arg.is_positional() {
        notes.push("Required.".to_string());
    }
    let values: Vec<String> = arg
        .get_possible_values()
        .iter()
        .filter(|v| !v.is_hide_set())
        .map(|v| format!("`{}`", v.get_name()))
        .collect();
    if !values.is_empty() && takes_value(arg) {
        notes.push(format!("One of {}.", values.join(", ")));
    }
    let defaults: Vec<String> = arg
        .get_default_values()
        .iter()
        .map(|v| v.to_string_lossy().into_owned())
        .collect();
    if !defaults.is_empty() && takes_value(arg) {
        notes.push(format!("Default: `{}`.", defaults.join(" ")));
    }
    if let Some(env) = arg.get_env() {
        notes.push(format!("Env: `{}`.", env.to_string_lossy()));
    }
    let aliases: Vec<String> = arg
        .get_all_aliases()
        .unwrap_or_default()
        .iter()
        .map(|a| format!("`--{a}`"))
        .collect();
    if !aliases.is_empty() {
        notes.push(format!("Also {}.", aliases.join(", ")));
    }
    for note in notes {
        if !text.is_empty() {
            text.push(' ');
        }
        text.push_str(&note);
    }
    text
}

/// Every variable a flag reads, then the ones the CLI reads itself.
fn environment(root: &Command) -> BTreeMap<String, String> {
    let mut vars = BTreeMap::new();
    collect_env(root, &mut vars);
    for (var, what) in ENVIRONMENT {
        vars.insert(var.to_string(), what.to_string());
    }
    vars
}

fn collect_env(cmd: &Command, vars: &mut BTreeMap<String, String>) {
    for arg in visible_args(cmd) {
        if let Some(env) = arg.get_env() {
            let help = arg
                .get_help()
                .map(|h| sentence(&h.to_string()))
                .unwrap_or_default();
            vars.entry(env.to_string_lossy().into_owned())
                .or_insert_with(|| format!("`{}`. {help}", flag(arg)).trim_end().to_string());
        }
    }
    for sub in cmd.get_subcommands() {
        collect_env(sub, vars);
    }
}

fn visible_args(cmd: &Command) -> impl Iterator<Item = &Arg> {
    cmd.get_arguments()
        .filter(|a| !a.is_hide_set() && !matches!(a.get_id().as_str(), "help" | "version"))
}

fn flag(arg: &Arg) -> String {
    let long = arg
        .get_long()
        .map(|l| format!("--{l}"))
        .unwrap_or_else(|| format!("-{}", arg.get_short().unwrap_or('?')));
    if takes_value(arg) {
        format!("{long} <{}>", value_name(arg))
    } else {
        long
    }
}

fn takes_value(arg: &Arg) -> bool {
    arg.get_action().takes_values()
}

fn value_name(arg: &Arg) -> String {
    arg.get_value_names()
        .map(|names| {
            names
                .iter()
                .map(|n| n.to_string())
                .collect::<Vec<_>>()
                .join(" ")
        })
        .unwrap_or_else(|| arg.get_id().as_str().to_uppercase())
}

/// Help text as one sentence: joined lines, a capital, a full stop, and
/// the flags it mentions set as code, as the rest of the page sets them.
fn sentence(text: &str) -> String {
    let joined = text
        .split_whitespace()
        .map(code_flag)
        .collect::<Vec<_>>()
        .join(" ");
    let mut chars = joined.chars();
    let mut out = match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect::<String>(),
        None => return String::new(),
    };
    if !out.ends_with(['.', '?', '!']) {
        out.push('.');
    }
    out
}

/// `--wait,` becomes `` `--wait`, ``; any other word is left as it is.
fn code_flag(word: &str) -> String {
    let flag = word.trim_end_matches([',', ';', '.', ')', ':']);
    if flag.len() > 2 && flag.starts_with("--") {
        format!("`{flag}`{}", &word[flag.len()..])
    } else {
        word.to_string()
    }
}

/// Text that sits in a table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use clap::CommandFactory;

    use super::render;
    use crate::Cli;

    #[test]
    fn the_page_has_every_command_and_flag() {
        let page = render(&Cli::command());
        for heading in [
            "### `wicket submit`",
            "### `wicket wait`",
            "### `wicket plugins`",
            "### `wicket plugins install`",
        ] {
            assert!(page.contains(heading), "{heading} is missing");
        }
        for flag in [
            "`--title <TITLE>`",
            "`--decision-out <FILE>`",
            "`--timeout <TIMEOUT>`",
            "`--url <URL>`",
        ] {
            assert!(page.contains(flag), "{flag} is missing");
        }
        assert!(page.contains("| `5` | The person discarded the review"));
        assert!(page.contains("`WICKET_REQUESTED_BY`"));
        assert!(page.starts_with("---\ntitle: CLI reference\n"));
    }
}
